name: Php aplication

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: nanasess/setup-php@master
    with:
      php-version: '7.4'
    - run: php script/build.php
